#!/bin/sh
PKG=/tmp/package-libtunepimp
rm -rf $PKG
mkdir -p $PKG

VERSION=0.4.2
ARCH=${ARCH:-x86_64}
BUILD=${BUILD:-5}
DISTRO=${DISTRO:-slamd64}

if [ $DISTRO = slackware ]; then
	PKGARCH=$ARCH
else
	PKGARCH=${ARCH}_${DISTRO}
fi

if [ $DISTRO = slamd64 ]; then
	LIBSUFFIX=${LIBSUFFIX:-64}
fi

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

CWD=`pwd` 
cd /tmp
rm -rf libtunepimp-$VERSION
tar xjvf $CWD/libtunepimp-$VERSION.tar.bz2
cd libtunepimp-$VERSION
zcat $CWD/libtunepimp.taglib-1.4.diff.gz | patch -p1 --verbose || exit 1
zcat $CWD/libtunepimp.CVE-2006-3600.diff.gz | patch -p1 --verbose || exit 1
chown -R root:root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 664 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --enable-static=no \
	--enable-shared \
	--libdir=/usr/lib$LIBSUFFIX \
  $ARCH-$DISTRO-linux 
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
mkdir -p $PKG/usr/doc/libtunepimp-$VERSION
cp -a \
  AUTHORS COPYING README README.LGPL TODO \
  $PKG/usr/doc/libtunepimp-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg -l y -c n /tmp/libtunepimp-$VERSION-$PKGARCH-$BUILD.tgz

