#!/bin/sh
CWD=`pwd`
PKG=/tmp/package-pcre

VERSION=7.0
ARCH=${ARCH:-x86_64}
BUILD=1

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

rm -rf $PKG
mkdir -p $PKG
cd /tmp
rm -rf pcre-$VERSION
tar xjvf $CWD/pcre-$VERSION.tar.bz2
cd pcre-$VERSION
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 664 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
./configure \
  --enable-utf8 \
  --prefix=/usr \
  --libdir=/usr/lib64
make -j 10
make install DESTDIR=$PKG
chmod 755 $PKG/usr/lib64/libpcre.so.* $PKG/usr/lib64/libpcreposix.so.*
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
mkdir -p $PKG/usr/doc/pcre-$VERSION
cp -a \
  AUTHORS COPYING INSTALL LICENCE NEWS NON-UNIX-USE README \
  $PKG/usr/doc/pcre-$VERSION
cd doc
cp -a Tech.Notes html $PKG/usr/doc/pcre-$VERSION
chown -R root.root $PKG/usr/doc/pcre-$VERSION
gzip -9 $PKG/usr/man/man?/*.?
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG

makepkg -l y -c n ../pcre-$VERSION-${ARCH}_slamd64-$BUILD.tgz

