#!/bin/sh
VERSION=4.1.2
OLDSOVER=5.0.7
ARCH=x86_64
BUILD=1
DISTRO=${DISTRO:-slamd64}

CWD=`pwd`

PKG=/tmp/package-aaa_elflibs32
PKGTMP=/tmp/cxxlibs32

rm -rf $PKGTMP
mkdir -p $PKGTMP
cd $PKGTMP

explodepkg $CWD/gcc32-g++-$VERSION-${ARCH}_${DISTRO}-$BUILD.tgz

cd usr/lib
install -o root -m 755 $CWD/libstdc++.so.$OLDSOVER .
ldconfig -n . # Recreate symlinks

mkdir -p $PKG/usr/lib
cp -a * $PKG/usr/lib
