#!/bin/bash
# Copyright (c) 2008, Fred Emmott <mail@fredemmott.co.uk>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

pkghelpers_fixup() {
	##### STRIP BINARIES #####
	find -type f | xargs file | grep ELF | cut -f1 -d: | xargs strip --strip-unneeded 2> /dev/null

	##### COMPRESS MAN PAGES #####
	if [ -d usr/man ]; then
		(
			cd usr/man
			find -type f -exec gzip -9 {} \;
			for deadlink in $(find -type l ! -iname "*.gz"); do
				ln -s $(readlink $deadlink).gz $deadlink.gz
				rm $deadlink
			done
		)
	fi

	##### COMPRESS INFO PAGES #####
	if [ -d usr/info ]; then
		rm -f usr/info/dir
		gzip -9 usr/info/*
	fi

	##### DELETE UNNECESSARY PERL DOCUMENTATION #####
	find . -name perllocal.pod | xargs rm -f
}
