#!/bin/sh
VERSION=2.0.0
ARCH=x86_64
BUILD=1
DISTRO=${DISTRO:-slamd64}

CWD=`pwd`

PKG=/tmp/package-aaa_elflibs32
TMP=/tmp/expat32-tmp
rm -rf $TMP
mkdir $TMP

cd $TMP

# Extract the stuff we want
tar --wildcards -xvf $CWD/expat32-$VERSION-${ARCH}_${DISTRO}-$BUILD.tgz usr/lib/*.so.*

# Recreate symlinks
cd usr/lib
ldconfig -n .

# Copy to package directory
mkdir -p $PKG/usr/lib
cp -a * $PKG/usr/lib
