#!/bin/sh
# Set initial variables:
CWD=$(pwd)
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-lha

VERSION=114i
ARCH=${ARCH:-x86_64}
BUILD=1
DISTRO=${DISTRO:-slamd64}

if [ $DISTRO = slackware ]; then
	PKGARCH=$ARCH
else
	PKGARCH=${ARCH}_${DISTRO}
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
rm -rf $PKG
mkdir -p $PKG

cd $TMP
rm -rf lha-114i
tar xzvf $CWD/lha-114i.tar.gz
cd lha-114i
zcat $CWD/lha_1.14i-10.1.diff.gz | patch -p1 --verbose || exit 1
patch -p0 < debian/patch.paul
patch -p0 < debian/patch.multibyte
patch -p0 < debian/patch.CAN-2004-0234_0235
patch -p0 < debian/patch.header-overflow
patch -p1 < debian/patch.redhat-sec2
patch -p1 < debian/patch.CVE-2006-4335-CVE-2006-4337-CVE-2006-4338
chown -R root:root .
make || exit 1
mkdir -p $PKG/usr/bin
cat src/lha > $PKG/usr/bin/lha
chmod 755 $PKG/usr/bin/lha
mkdir -p $PKG/usr/man/man1
cat debian/lha.1 | gzip -9 > $PKG/usr/man/man1/lha.1.gz
mkdir -p $PKG/usr/man/jp/man1
cat man/lha.man | gzip -9 > $PKG/usr/man/jp/man1/lha.1.gz
mkdir -p $PKG/usr/doc/lha-114i
cp -a \
  change-${VERSION}.txt \
  $PKG/usr/doc/lha-${VERSION}
mkdir -p $PKG/usr/doc/lha-${VERSION}/jp
cp -a *.euc \
  $PKG/usr/doc/lha-${VERSION}/jp
chmod 644 $PKG/usr/man/jp/man1/*

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/lha-$VERSION-$PKGARCH-$BUILD.tgz

